// <auto-generated />
using CSharp_Entity_Framework_Players;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpEntityFrameworkPlayers.Migrations
{
    [DbContext(typeof(TeamContext))]
    partial class TeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSharp_Entity_Framework_Players.Player", b =>
                {
                    b.Property<int>("GiocatoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("primary_Key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiocatoreID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartiteGiocate")
                        .HasColumnType("int")
                        .HasColumnName("partite_giocate");

                    b.Property<int>("PartiteVinte")
                        .HasColumnType("int")
                        .HasColumnName("partite_vinte");

                    b.Property<float>("Punteggio")
                        .HasColumnType("real")
                        .HasColumnName("punteggio");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GiocatoreID");

                    b.HasIndex("GiocatoreID")
                        .IsUnique();

                    b.ToTable("giocatori");
                });
#pragma warning restore 612, 618
        }
    }
}
